let box = document.getElementById('b1')
let sp1 = document.getElementById('sp1')
console.log(box)
console.log(box.matches('.class'))
console.log(box.matches('.box'))
console.log(sp1.closest('#sp1'))
console.log(b1.contains(sp1))
console.log(sp1.contains(sp1))
console.log(sp1.contains(b1))